/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as R404RouteImport } from './routes/404'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AustralianBusinessesRouteImport } from './routes/australian-businesses'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as ManufacturersRouteImport } from './routes/manufacturers'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as SolutionsIndexRouteImport } from './routes/solutions.index'
import { Route as SolutionsCncFabricationRouteImport } from './routes/solutions.cnc-fabrication'
import { Route as SolutionsPackagingProcessingRouteImport } from './routes/solutions.packaging-processing'
import { Route as SolutionsWarehouseAutomationRouteImport } from './routes/solutions.warehouse-automation'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AustralianBusinessesRoute = AustralianBusinessesRouteImport.update({
  id: '/australian-businesses',
  path: '/australian-businesses',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const ManufacturersRoute = ManufacturersRouteImport.update({
  id: '/manufacturers',
  path: '/manufacturers',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsIndexRoute = SolutionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SolutionsRoute,
} as any)
const SolutionsCncFabricationRoute = SolutionsCncFabricationRouteImport.update({
  id: '/cnc-fabrication',
  path: '/cnc-fabrication',
  getParentRoute: () => SolutionsRoute,
} as any)
const SolutionsPackagingProcessingRoute =
  SolutionsPackagingProcessingRouteImport.update({
    id: '/packaging-processing',
    path: '/packaging-processing',
    getParentRoute: () => SolutionsRoute,
  } as any)
const SolutionsWarehouseAutomationRoute =
  SolutionsWarehouseAutomationRouteImport.update({
    id: '/warehouse-automation',
    path: '/warehouse-automation',
    getParentRoute: () => SolutionsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/about': typeof AboutRoute
  '/australian-businesses': typeof AustralianBusinessesRoute
  '/contact': typeof ContactRoute
  '/how-it-works': typeof HowItWorksRoute
  '/manufacturers': typeof ManufacturersRoute
  '/solutions': typeof SolutionsRouteWithChildren
  '/solutions/cnc-fabrication': typeof SolutionsCncFabricationRoute
  '/solutions/packaging-processing': typeof SolutionsPackagingProcessingRoute
  '/solutions/warehouse-automation': typeof SolutionsWarehouseAutomationRoute
  '/solutions/': typeof SolutionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/about': typeof AboutRoute
  '/australian-businesses': typeof AustralianBusinessesRoute
  '/contact': typeof ContactRoute
  '/how-it-works': typeof HowItWorksRoute
  '/manufacturers': typeof ManufacturersRoute
  '/solutions/cnc-fabrication': typeof SolutionsCncFabricationRoute
  '/solutions/packaging-processing': typeof SolutionsPackagingProcessingRoute
  '/solutions/warehouse-automation': typeof SolutionsWarehouseAutomationRoute
  '/solutions': typeof SolutionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/about': typeof AboutRoute
  '/australian-businesses': typeof AustralianBusinessesRoute
  '/contact': typeof ContactRoute
  '/how-it-works': typeof HowItWorksRoute
  '/manufacturers': typeof ManufacturersRoute
  '/solutions': typeof SolutionsRouteWithChildren
  '/solutions/cnc-fabrication': typeof SolutionsCncFabricationRoute
  '/solutions/packaging-processing': typeof SolutionsPackagingProcessingRoute
  '/solutions/warehouse-automation': typeof SolutionsWarehouseAutomationRoute
  '/solutions/': typeof SolutionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/404'
    | '/about'
    | '/australian-businesses'
    | '/contact'
    | '/how-it-works'
    | '/manufacturers'
    | '/solutions'
    | '/solutions/cnc-fabrication'
    | '/solutions/packaging-processing'
    | '/solutions/warehouse-automation'
    | '/solutions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/404'
    | '/about'
    | '/australian-businesses'
    | '/contact'
    | '/how-it-works'
    | '/manufacturers'
    | '/solutions/cnc-fabrication'
    | '/solutions/packaging-processing'
    | '/solutions/warehouse-automation'
    | '/solutions'
  id:
    | '__root__'
    | '/'
    | '/404'
    | '/about'
    | '/australian-businesses'
    | '/contact'
    | '/how-it-works'
    | '/manufacturers'
    | '/solutions'
    | '/solutions/cnc-fabrication'
    | '/solutions/packaging-processing'
    | '/solutions/warehouse-automation'
    | '/solutions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R404Route: typeof R404Route
  AboutRoute: typeof AboutRoute
  AustralianBusinessesRoute: typeof AustralianBusinessesRoute
  ContactRoute: typeof ContactRoute
  HowItWorksRoute: typeof HowItWorksRoute
  ManufacturersRoute: typeof ManufacturersRoute
  SolutionsRoute: typeof SolutionsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/australian-businesses': {
      id: '/australian-businesses'
      path: '/australian-businesses'
      fullPath: '/australian-businesses'
      preLoaderRoute: typeof AustralianBusinessesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manufacturers': {
      id: '/manufacturers'
      path: '/manufacturers'
      fullPath: '/manufacturers'
      preLoaderRoute: typeof ManufacturersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/': {
      id: '/solutions/'
      path: '/'
      fullPath: '/solutions/'
      preLoaderRoute: typeof SolutionsIndexRouteImport
      parentRoute: typeof SolutionsRoute
    }
    '/solutions/cnc-fabrication': {
      id: '/solutions/cnc-fabrication'
      path: '/cnc-fabrication'
      fullPath: '/solutions/cnc-fabrication'
      preLoaderRoute: typeof SolutionsCncFabricationRouteImport
      parentRoute: typeof SolutionsRoute
    }
    '/solutions/packaging-processing': {
      id: '/solutions/packaging-processing'
      path: '/packaging-processing'
      fullPath: '/solutions/packaging-processing'
      preLoaderRoute: typeof SolutionsPackagingProcessingRouteImport
      parentRoute: typeof SolutionsRoute
    }
    '/solutions/warehouse-automation': {
      id: '/solutions/warehouse-automation'
      path: '/warehouse-automation'
      fullPath: '/solutions/warehouse-automation'
      preLoaderRoute: typeof SolutionsWarehouseAutomationRouteImport
      parentRoute: typeof SolutionsRoute
    }
  }
}

interface SolutionsRouteChildren {
  SolutionsCncFabricationRoute: typeof SolutionsCncFabricationRoute
  SolutionsPackagingProcessingRoute: typeof SolutionsPackagingProcessingRoute
  SolutionsWarehouseAutomationRoute: typeof SolutionsWarehouseAutomationRoute
  SolutionsIndexRoute: typeof SolutionsIndexRoute
}

const SolutionsRouteChildren: SolutionsRouteChildren = {
  SolutionsCncFabricationRoute: SolutionsCncFabricationRoute,
  SolutionsPackagingProcessingRoute: SolutionsPackagingProcessingRoute,
  SolutionsWarehouseAutomationRoute: SolutionsWarehouseAutomationRoute,
  SolutionsIndexRoute: SolutionsIndexRoute,
}

const SolutionsRouteWithChildren = SolutionsRoute._addFileChildren(
  SolutionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R404Route: R404Route,
  AboutRoute: AboutRoute,
  AustralianBusinessesRoute: AustralianBusinessesRoute,
  ContactRoute: ContactRoute,
  HowItWorksRoute: HowItWorksRoute,
  ManufacturersRoute: ManufacturersRoute,
  SolutionsRoute: SolutionsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
